name: DEEEEDeploy to Development Environment
on:
  push:
    branches:
       - master
  pull_request:
    branches:
       - PrepRod
env:
  
  AZURE_DEVWEBAPP_NAME: GitAc-Dev
  AZURE_PREPRODWEBAPP_NAME: GitAc-PreProd
  AZURE_WEBAPP_PACKAGE_PATH: 'D:\a\GitNewTest2\GitNewTest2\GitNewTest2\bin'
jobs:
  Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore GitNewTest2/GitNewTest2.sln

    - name: build
      run: |
           msbuild GitNewTest2/GitNewTest2.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
    - name: publish
      run: |
           msbuild GitNewTest2/GitNewTest2.sln /t:Publish /p:Configuration=Release /p:Platform="Any CPU" /p:PublishDir="./artifacts"
   
      
      #--output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
      
#    - name: Upload artifacts
 #     uses: actions/upload-artifact@v2
  #    with:
   #     name: MyProject artifacts
    #    path: bin/Release
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
            name: myapp
            path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
            
    - name: running1
      run: |
           Get-location
           
    - name: running6
      run: |
           dir D:\a\GitNewTest2\GitNewTest2\GitNewTest2\bin
         
  #  - name: Extract artifacts
   #   uses: actions/extract-archive@v2
    #  with:
     #  archive-file: ${{github.workspace}}
      # output-directory: ${{github.workspace}}
    #- name: run     
     # run: |
      #     dir ./artifacts
       #    dir
        #   cd GitNewTest2
         #  dir
          # cd bin
           #dir
#   DeployDev:
#       name: Dev
#       needs: Build
# #       if: github.event_name == 'refs/heads/master'
#       runs-on: windows-latest
# #       env:
# #         DEPLOYMENT_ENVIRONMENT: Dev
# #         AZURE_DEVWEBAPP_NAME: GitAc-Dev
# #         AZURE_PREPRODWEBAPP_NAME: GitAc-PreProd
# #         AZURE_WEBAPP_PACKAGE_PATH: 'D:\a\GitNewTest2\GitNewTest2\bin\'
#       environment:
#           name: Dev
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: myapp
        path: 'C:\app.publish'
    - name: running
      run: |
           Get-location
           
    - name: running2
      run: |
           dir
           
    - name: running3
      run: |
           cd C:\app.publish
           dir
           
    - name: Install Web Deploy
      run: |
          Invoke-WebRequest https://download.microsoft.com/download/9/1/7/917AEB5A-79A9-46D3-8F88-2C1F585C5984/WebDeploy_amd64_en-US.msi -OutFile webdeploy.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/i webdeploy.msi /qn /norestart'


#        - name: Deploy
#          uses: Azure/webapps-deploy@v2
#          with:
#             app-name: ${{env.AZURE_DEVWEBAPP_NAME}}
#             publish-profile: ${{secrets.AZURE_DEVPUBLISH_PROFILE}}
#             package: artifacts/
#   DeployDev:
#       name: Dev
#       needs: Build
# #       if: github.event_name == 'refs/heads/master'
#       runs-on: self-hosted
#       env:
#         DEV_WEBSITE_NAME: ${{secrets.DEV_WEBSITE_NAME}}
#         DEV_APP_POOL_NAME: ${{secrets.DEV_APP_POOL_NAME}}
# #         WEBAPP_MSDeploy_USERNAME: ${{secrets.IIS_USERNAME}}
# #         WEBAPP_MSDeploy_PASSWORD: ${{secrets.IIS_PASSWORD}}
#       environment:
#           name: Dev
#       steps:
#       # - name: Download artifacts
#        #  uses: actions/download-artifact@v2
#         # with:
#          # name: myapp
#           #path: artifacts/
#        - name: copying
#          run: |
#               Set-ExecutionPolicy RemoteSigned
#               & C:\actions-runner5\_work\Git_Final_Test\Git_Final_Test\Git_Final_Test\Psscripts\DevTestScript.ps1
        
#               cd C:\inetpub\wwwroot\
 
#               Copy-Item C:\actions-runner5\_work\Git_Final_Test\Git_Final_Test\Git_Final_Test\* C:\inetpub\wwwroot\${{env.DEV_WEBSITE_NAME}} -Recurse -Force

#        - name: create new apppool
#          run: |
#              & C:\actions-runner5\_work\Git_Final_Test\Git_Final_Test\Git_Final_Test\Psscripts\DevTestAppPool.ps1
#        - name: create website
#          run: |
#               & C:\actions-runner5\_work\Git_Final_Test\Git_Final_Test\Git_Final_Test\Psscripts\DevTestWebsite.ps1
#        - name: config to use new appool
#          run: |
#              Import-Module WebAdministration
#              Set-ItemProperty -Path "IIS:\Sites\${{env.DEV_WEBSITE_NAME}}" -Name "applicationPool" -Value ${{env.DEV_APP_POOL_NAME}}

         
       
#        - name: Deploy to IIS
#          run: |
#               # start-process PowerShell -verb runas 
#               iisreset /stop
#               iisreset /start

